sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t CI=true pkdocker/docker-react -f Dockerfile.dev .

script:
    - docker run pkdocker/docker-react npm run test -- --coverage