FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

# Docker compose can be made to replace this copy so that reference can be used instead of copy
COPY . . 

CMD ["npm", "run", "start"]